name: Docker Slim

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install docker-slim
        run: |
          curl -sL https://github.com/docker-slim/docker-slim/releases/download/v1.34.0/docker-slim-1.34.0-linux-amd64.tar.gz | tar -xz
          sudo mv docker-slim-1.34.0-linux-amd64/docker-slim /usr/local/bin/
          sudo chmod +x /usr/local/bin/docker-slim

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push the image
        run: |
          docker build -t mkdocs-image -f Dockerfile.mkdocs .
          docker tag mkdocs-image ghcr.io/${GITHUB_REPOSITORY}/mkdocs-image:latest
          docker push ghcr.io/${GITHUB_REPOSITORY}/mkdocs-image:latest

          docker-slim build --tag ghcr.io/${GITHUB_REPOSITORY}/slim-image:latest mkdocs-image
          docker push ghcr.io/${GITHUB_REPOSITORY}/slim-image:latest
